const list = [
  {
    id: 1,
    title: "BODYFIT Home Gym Combo Set, Gym Equipments, [8Kg-100 Kg], 3ft Curl, 5Ft Straight Rod + One Pair Dumbbell Rods, PVC Dumbbell Plates, Weight Plates, Home Gym Kit, Exercise Set. (20KG Combo Set) - Black",
    author: " BODYFIT",
    price: 1345,
    img: "../1.webp",
    amount: 1,
  },
  {
    id: 2,
    title: "LEEWAY Hex Dumbbells Pack (2.5 kg*2)| Gym Dumbbells| Rubber Coating Free Weight Dumbbell Set| Rubber Encased Hex Fixed Dumbbell Weight| Professional Rubber Coated Hexa Dumbbells (2.5Kg Pair)(Black)",
    author: "LEEWAY Hex Dumbbells",
    price: 1103,
    img: "../1.jpg",
    amount: 1,
  },
  {
    id: 3,
    title: "BLUMORA Exercise Bands Resistance Bands Set for Workingout Door Fitness Gym Resistance Bands Kit for Men Women Streching Rubber Bands (11PCS)",
    Brand: "BLUMORA",
    price: 460,
    img: "./2.jpg",
    amount: 1,
  },
  {
    id: 4,
    title: " NoiseFree Spin Bike (Flywheel- 6kg, Max weight- 120 kg, Resistance Mechanism - Magnetic) (6 months warranty) (Black)",
    author: "by Wonder House Books | 25 April 2018",
    price: 19279,
    img: "./3.webp",
    amount: 1,
  },
  {
    id: 5,
    title: "sport bag for gym and travel with spider protein shaker bottle Fitness Accessory Kit Kit",
    author: "EMMKITZ",
    price: 399,
    img: "./4.webp",
    amount: 1,
  },
  {
    id: 6,
    title: "ADONYX Toning Tube With Skipping Rope, Speed Rope For fitness, endurance & weight loss Gym & Fitness Kit",
    author: "ADONYX",
    price: 275,
    img: "./5.webp",
    amount: 1,
  },
  {
    id: 7,
    title: "HRX Professional Rubber Plates Kit Set with 3 Ft Curl, 5 Ft Plain and 1 Pair Dm Rods Home Gym Kit",
    author: "HRX Professional",
    price: 10465,
    img: "./6.webp",
    amount: 1,
  },
  {
    id: 8,
    title: "B FIT USA B Fit 4D PRO Re Action Trainer Fitness Accessory Kit Kit",
    author: "B FIT USA B Fit",
    price: 7499,
    img: "./7.webp",
    amount: 1,
  },
  {
    id: 9,
    title: "DANIKA SEHGAL Marker Cone 42 Set- 42 Hurdles, 20 Cones With Holder, Ladder, Resistance Parachute, Jump Rope, Resistance Bands Agility Ladder Fitness Accessory Kit Kit ",
    author: "DANIKA SEHGAL Marker Cone",
    price: 6998,
    img: "./8.webp",
    amount: 1,
  },
  {
    id: 10,
    title: "Tunturi Pilates Fitness Accessory Kit Kit",
    author: "Tunturi Pilates",
    price: 1999,
    img: "9.webp",
    amount: 1,
  },
  {
    id: 11,
    title: "Sketra Hyper Multi Station Gym",
    author: "Sketra Hyper",
    price: 72999,
    img: "11.jpg",
    amount: 1,
  },
  {
    id: 12,
    title: "MC-250 Five Station Multi Gym for Multiple Workouts",
    author: "Five Station",
    price: 65999,
    img: "10.webp",
    amount: 1,
  },
];

export default list;
